name: Update Hugo Modules

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

defaults:
  run:
    shell: pwsh

jobs:
  update_hugo_modules:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Hugo
        id: setup-hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Update Modules
        id: update-modules
        run: |
          $UpdateLines = Invoke-Command { hugo mod get -u ./... 2>&1 } |
            ForEach-Object { $_.ToString() } |
            Where-Object -FilterScript {
              # Skip generic update line
              $_.ToString() -notmatch '^Update module in'
            }
          If ($UpdateLines -match '(error|failed to execute)') {
            Throw "Something went wrong!`r`n$UpdateLines"
          } Else {
            $UpdateLines = $UpdateLines -join "`r`n" | ConvertTo-Json
          }
          echo "::set-output name=updates::$UpdateLines"
      - name: Create Pull Request
        id: createpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: (MAINT) Update Hugo Modules
          title: (MAINT) Update Hugo Modules
          body: |
            Dependency updates:

            ```text
            ${{ fromJSON(steps.update-modules.outputs.updates) }}
            ```

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-hugo-modules
          base: main
          delete-branch: true
